#!/bin/bash
BENCHMARK_FLAG=-b
GUI_FLAG=-g

usage() {
    echo "Usage: $0 <$BENCHMARK_FLAG|$GUI_FLAG>" >&2
    echo -e "\t$0 $BENCHMARK_FLAG run benchmark"
    echo -e "\t$0 $GUI_FLAG run GUI"
}

if [ "$#" -ne "1" ]; then
    usage >&2
    exit 1
elif [[ "$1" == $BENCHMARK_FLAG ]]; then
    baseName=benchmark
elif [[ "$1" == $GUI_FLAG ]]; then
    baseName=launcher
else
    usage >&2
    exit 1
fi

java -jar build/libs/$baseName-1.0.jar
